// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BHrFPF1NfYrzGi0zyyDafgfHtSqXVOY',
    appId: '1:215389923899:web:7ba9633da4701e5e9e0a1e',
    messagingSenderId: '215389923899',
    projectId: 'gelle-a6303',
    authDomain: 'gelle-a6303.firebaseapp.com',
    storageBucket: 'gelle-a6303.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2jb7QV7K2jw0YJ3ZCrXLPkhf6fJuHR40',
    appId: '1:215389923899:android:ebd9a162d247df0c9e0a1e',
    messagingSenderId: '215389923899',
    projectId: 'gelle-a6303',
    storageBucket: 'gelle-a6303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzG1rt45JrbGujL7ecfx17IV_8-vRA7tk',
    appId: '1:215389923899:ios:10d19322f0fe3cd89e0a1e',
    messagingSenderId: '215389923899',
    projectId: 'gelle-a6303',
    storageBucket: 'gelle-a6303.appspot.com',
    iosClientId: '215389923899-be97folbdfhc8lbgcvtbg5oron1l2kgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.formfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzG1rt45JrbGujL7ecfx17IV_8-vRA7tk',
    appId: '1:215389923899:ios:10d19322f0fe3cd89e0a1e',
    messagingSenderId: '215389923899',
    projectId: 'gelle-a6303',
    storageBucket: 'gelle-a6303.appspot.com',
    iosClientId: '215389923899-be97folbdfhc8lbgcvtbg5oron1l2kgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.formfirebase',
  );
}
